Repository 2024-Summer-Bootcamp-Team-I/Backend, pull requests merged in 2024-07, with the labels that each got.

#15 [feat] 회원가입 및 로그인 구현
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_customuser_nickname.py
  accounts/migrations/0003_user_delete_customuser.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  djangoIteam/settings.py
  djangoIteam/urls.py
Labels: 기능구현

#16 [feat] 피드백 생성 및 조회 구현 완료
  accounts/models.py
  accounts/serializers.py
  classify_news/__init__.py
  classify_news/admin.py
  classify_news/apps.py
  classify_news/migrations/0001_initial.py
  classify_news/migrations/__init__.py
  classify_news/models.py
  classify_news/serializers.py
  classify_news/tests.py
  classify_news/urls.py
  classify_news/views.py
  djangoIteam/settings.py
  djangoIteam/urls.py
  feedbacks/__init__.py
  feedbacks/admin.py
  feedbacks/apps.py
  feedbacks/migrations/0001_initial.py
  feedbacks/migrations/__init__.py
  feedbacks/models.py
  feedbacks/serializers.py
  feedbacks/tests.py
  feedbacks/urls.py
  feedbacks/views.py
  news/__init__.py
  news/admin.py
  news/apps.py
  news/migrations/0001_initial.py
  news/migrations/__init__.py
  news/models.py
  news/tests.py
  news/views.py
Labels: 기능구현

#17 [feat] 로그인 회원가입 변수명 수정
  accounts/migrations/0004_rename_user_name_user_email.py
  accounts/migrations/0005_rename_create_at_user_created_at_and_more.py
  accounts/migrations/0006_alter_user_is_deleted.py
  accounts/migrations/0007_alter_user_is_deleted.py
  accounts/models.py
  accounts/serializers.py
  accounts/views.py
Labels: 오류수정, 기능구현

#23 [feat] 뉴스 기사 저장 및 조회기능 구현
  classify_news/migrations/0002_rename_create_at_classifynews_created_at_and_more.py
  djangoIteam/settings.py
  djangoIteam/urls.py
  feedbacks/migrations/0002_rename_create_at_feedback_created_at_and_more.py
  news/migrations/0001_initial.py
  news/migrations/0002_rename_is_deleted_news_is_deleated.py
  news/migrations/0003_alter_news_channel_id.py
  news/models.py
  news/serializers.py
  news/urls.py
  news/views.py
Labels: 기능구현

#25 [feat] 판별 기사 CRUD 구현
  channels/__init__.py
  channels/admin.py
  channels/apps.py
  channels/migrations/__init__.py
  channels/models.py
  channels/tests.py
  channels/views.py
  classify_news/migrations/0002_rename_create_at_classifynews_created_at_and_more.py
  classify_news/models.py
  classify_news/serializers.py
  classify_news/urls.py
  classify_news/views.py
  djangoIteam/settings.py
  djangoIteam/urls.py
  feedbacks/migrations/0002_rename_create_at_feedback_created_at_and_more.py
  feedbacks/models.py
  news/migrations/0002_rename_create_at_news_created_at_and_more.py
  news/migrations/0003_rename_is_deleated_news_is_deleted.py
  news/models.py
  news/serializers.py
Labels: 기능구현

#19 [feat] 언론사 저장 및 점수 조회
  accounts/views.py
  channels/migrations/0001_initial.py
  channels/migrations/0002_alter_channel_id.py
  channels/migrations/0003_alter_channel_is_deleted_alter_channel_logo_and_more.py
  channels/migrations/0004_alter_channelscore_id.py
  channels/migrations/0005_remove_channelscore_updated_at.py
  channels/migrations/0006_channelscore_updated_at.py
  channels/models.py
  channels/serializers.py
  channels/urls.py
  channels/views.py
  classify_news/migrations/0003_remove_classifynews_is_faked_and_more.py
  classify_news/migrations/0004_rename_deleted_at_classifynews_is_deleted.py
  classify_news/models.py
  classify_news/serializers.py
  classify_news/urls.py
  classify_news/views.py
  djangoIteam/settings.py
  djangoIteam/urls.py
  feedbacks/migrations/0002_rename_create_at_feedback_created_at_and_more.py
  feedbacks/migrations/0003_rename_feedback_id_feedback_id_and_more.py
  feedbacks/models.py
  feedbacks/views.py
  news/migrations/0001_initial.py
  news/migrations/0002_alter_news_channel_alter_news_is_deleted_and_more.py
  news/models.py
  news/serializers.py
  news/views.py
Labels: 기능구현

#28 [feat] 언론사 점수 조회
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_customuser_nickname.py
  accounts/migrations/0003_user_delete_customuser.py
  accounts/migrations/0004_rename_user_name_user_email.py
  accounts/migrations/0005_rename_create_at_user_created_at_and_more.py
  accounts/migrations/0006_remove_user_is_deleted.py
  channels/migrations/0001_initial.py
  channels/migrations/0002_alter_channel_id.py
  channels/migrations/0003_alter_channel_is_deleted_alter_channel_logo_and_more.py
  channels/migrations/0004_alter_channelscore_id.py
  channels/migrations/0005_remove_channelscore_updated_at.py
  channels/migrations/0006_channelscore_updated_at.py
  channels/serializers.py
  channels/urls.py
  channels/views.py
  classify_news/migrations/0001_initial.py
  classify_news/migrations/0002_alter_classifynews_is_deleted.py
  classify_news/migrations/0002_rename_create_at_classifynews_created_at_and_more.py
  classify_news/migrations/0003_remove_classifynews_is_faked_and_more.py
  classify_news/migrations/0004_rename_deleted_at_classifynews_is_deleted.py
  classify_news/models.py
  djangoIteam/settings.py
  feedbacks/migrations/0001_initial.py
  feedbacks/migrations/0002_rename_create_at_feedback_created_at_and_more.py
  feedbacks/migrations/0003_rename_feedback_id_feedback_id_and_more.py
  news/migrations/0001_initial.py
  news/migrations/0002_alter_news_channel_alter_news_is_deleted_and_more.py
  news/migrations/0002_rename_create_at_news_created_at_and_more.py
  news/migrations/0002_rename_is_deleted_news_is_deleated.py
  news/migrations/0003_alter_news_channel_id.py
  news/migrations/0003_news_image.py
  news/migrations/0003_rename_is_deleated_news_is_deleted.py
Labels: 기능구현

#32 [chore] 백엔드 도커 세팅 완료
  Dockerfile
  djangoIteam/settings.py
  docker-compose.yml
  requirements.txt
Labels: 기타/세팅

#35 [feat] 기사 페이지네이션
  classify_news/serializers.py
  classify_news/views.py
Labels: 기능구현

#39 [feat] 모니터링 코드 구현
  docker-compose.yml
  news/crowling.py
  news/migrations/0005_news_url.py
  news/models.py
  news/views.py
  prometheus.yml
  requirements.txt
Labels: 기능구현

#40 [feat] 회원가입 닉네임 제거
  accounts/migrations/0002_remove_user_nickname.py
  accounts/models.py
  accounts/serializers.py
Labels: 오류수정

#46 [feat] 스크랩 뉴스 수정
  scraped_news/serializers.py
  scraped_news/views.py
Labels: 기능구현

#48 [feat] 요약 추가완료, 이메일 오류메세지 수정
  accounts/views.py
  news/crowling.py
  news/migrations/0006_news_summarize.py
  news/migrations/0007_alter_news_img.py
  news/migrations/0008_alter_news_summarize.py
  news/migrations/0009_alter_news_published_date_alter_news_summarize.py
  news/models.py
  news/views.py
Labels: 기능구현

#50 [feat] 스크랩 뉴스 Response값 변경
  scraped_news/serializers.py
Labels: 기능구현

#51 [feat] 스크랩 뉴스 삭제로직 수정
  djangoIteam/settings.py
  requirements.txt
  scraped_news/views.py
Labels: 오류수정

#53 [feat] 스크랩 기사 삭제 연산 수정
  scraped_news/views.py
Labels: 기능구현

#55 [feat] 뉴스기사 개수 조회 구현
  news/serializers.py
  news/urls.py
  news/views.py
Labels: 기능구현

#60 [feat] 구글키 업로드
  .gitignore
  Dockerfile
  classify_news/sentiment.py
  docker-compose.yml
Labels: 오류수정

#63 [feat] 뉴스 타입 칼럼 추가
  classify_news/embedding.py
  news/migrations/0010_news_type.py
  news/models.py
Labels: 기능구현

#65 [feat] 유형A조회 respose값 변경
  classify_news/views.py
Labels: 오류수정

#67 [feat] 이미지랑 요약추가
  classify_news/views.py
Labels: 오류수정

#69 [feat] 타임라인 기능 구현
  classify_news/03_QA.py
  classify_news/embedding.py
  classify_news/news_data.txt
  news/crowling.py
  news/serializers.py
  news/timeline.py
  news/urls.py
  news/views.py
  requirements.txt
Labels: 기능구현

#73 [feat] 기사 개수 조회 일자범위 증가
  news/views.py
Labels: 기능구현

#75 [feat] 로그인 response 값 추가
  accounts/views.py
Labels: 기능구현

#77 [feat] 타임라인 로직 수정
  docker-compose.yml
  news/timeline.py
  requirements.txt
Labels: 기능구현

#79 [feat] 뉴스 크롤링 임베딩 연결
  Dockerfile
  classify_news/news_data.txt
  djangoIteam/urls.py
  news/crowling.py
  news/news_embedding.py
  requirements.txt
Labels: 기능구현

#80 [feat] nginx 배포를 위한 merge필요
  Dockerfile
  djangoIteam/settings.py
  djangoIteam/urls.py
  docker-compose.yml
  nginx.conf
  requirements.txt
Labels: 기능구현

#83 [fix] Swagger ui 오류수정
  .gitignore
  djangoIteam/settings.py
  djangoIteam/urls.py
  docker-compose.yml
  nginx.conf
  staticfiles/favicon-16x16.png
  staticfiles/favicon-32x32.png
  staticfiles/index.css
  staticfiles/index.html
  staticfiles/oauth2-redirect.html
  staticfiles/swagger-initializer.js
  staticfiles/swagger-ui-bundle.js
  staticfiles/swagger-ui-bundle.js.map
  staticfiles/swagger-ui-es-bundle-core.js
  staticfiles/swagger-ui-es-bundle-core.js.map
  staticfiles/swagger-ui-es-bundle.js
  staticfiles/swagger-ui-es-bundle.js.map
  staticfiles/swagger-ui-standalone-preset.js
  staticfiles/swagger-ui-standalone-preset.js.map
  staticfiles/swagger-ui.css
  staticfiles/swagger-ui.css.map
  staticfiles/swagger-ui.js
  staticfiles/swagger-ui.js.map
Labels: 오류수정

#84 [feat] ci/cd 구축 시도
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.sh
  .gitignore
Labels: 기능구현

#90 [feat] 페이지네이션 전체페이지 수 반환
  classify_news/views.py
Labels: 기능구현

#92 [feat] 판별뉴스 정보 채널이름 추가
  classify_news/serializers.py
Labels: 기능구현

#94 [fix] 언론사 이름 추가 오류 수정
  classify_news/serializers.py
Labels: 기능구현

#97 [feat] 회원 이메일 길이 증가
  accounts/models.py
Labels: 기능구현

#88 [fix] CI완성, CD코드 작성완료, 오류발생시 수정예정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.sh
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
Labels: 오류수정

#100 [fix] secrets.docker_registry추
  .github/workflows/ci.yml
  news/views.py
Labels: 오류수정

#101 [feat] SNU 임베딩, 판별 기능 구현
  accounts/migrations/0003_alter_user_email.py
  classify_news/serializers.py
  classify_news/snu_classify_c_news.py
  classify_news/snu_content.txt
  classify_news/snu_crawl.py
  classify_news/snu_embedding.py
  classify_news/snu_save_c_news.py
  classify_news/urls.py
  classify_news/views.py
Labels: 기능구현

#106 [fix] 똑같은 인증 토큰 사용하여 재시도
  .github/workflows/ci.yml
Labels: 오류수정

#108 [fix] CI, CD변경
  .github/workflows/ci.yml
  .github/workflows/deploy.sh
  .github/workflows/deploy.yml
  requirements.txt
Labels: 오류수정

#112 [Fix] requirement에 종속성추가
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  accounts/migrations/0003_alter_user_email.py
  news/news_content.txt
  news/views.py
  requirements.txt
Labels: 오류수정

#113 [feat] 통계값 API 추가 구현
  classify_news/snu_embedding.py
  news/news_content.txt
  news/urls.py
  news/views.py
  scraped_news/migrations/0001_initial.py
  scraped_news/models.py
Labels: 기능구현

#116 [fix] 모니터링 툴 backend도 연결한거
  .github/workflows/deploy.sh
  djangoIteam/settings.py
  djangoIteam/urls.py
  docker-compose.yml
  nginx.conf
  prometheus.yml
  prometheus/config/prometheus.yml
  requirements.txt
Labels: 오류수정

#119 [fix] cd ec2에 자동적용 오류
  .github/workflows/ci.yml
  .github/workflows/deploy.sh
  news/views.py
  prometheus/config/prometheus.yml
Labels: 오류수정

#120 [fix] :자동 배포 해결완, 모니터링 툴은 잘 켜지는지 try
  .github/workflows/deploy.sh
Labels: 오류수정

#123 [feat] 스크랩 기사 검색 기능 구현
  scraped_news/serializers.py
  scraped_news/urls.py
  scraped_news/views.py
Labels: 기능구현

#124 [feat] 판별기사 전체조회에 검색 조건 추가
  classify_news/serializers.py
  classify_news/views.py
Labels: 기능구현

#121 [fix] docker hub에 저장한 이미지 사용
  docker-compose.yml
  news/views.py
Labels: 오류수정

#127 [fix] 뉴스기사저장 이름변경
  news/views.py
Labels: 오류수정

#128 [chore] Opensearch 세팅 완료
  classify_news/snu_classify_c_news.py
  news/news_embedding.py
  news/timeline.py
Labels: 기타/세팅

#129 [fix] cd확인을 위한 단순 이름변경
  djangoIteam/urls.py
  news/views.py
Labels: 오류수정

#130 [fix] 컴포즈 오류 해결 체크
  news/views.py
Labels: 오류수정

#131 Revert "[fix] docker hub에 저장한 이미지 사용"
  docker-compose.yml
Labels: 오류수정

#133 [fix] 프론트 요구사항 반영
  Dockerfile
  djangoIteam/settings.py
  news/views.py
  scraped_news/views.py
Labels: 오류수정

#135 [fix] github secret 추가
  .github/workflows/deploy.sh
  .github/workflows/deploy.yml
  news/views.py
Labels: 오류수정

#136 [fix] deploy.yml 공백제거
  .github/workflows/deploy.yml
Labels: 오류수정

#138 [fix] nginx, compose.yml 교체
  .github/workflows/deploy.sh
  djangoIteam/settings.py
  djangoIteam/urls.py
  docker-compose.yml
  nginx.conf
Labels: 오류수정

#139 [fix] openapi 오류 수정
  djangoIteam/urls.py
  news/views.py
Labels: 오류수정
